{
	"th01": "Touhou Rei'iden - Highly Responsive to Prayers",
	"th02": "Touhou Fuumaroku - The Story of Eastern Wonderland",
	"th03": "Touhou Yumejikuu - Phantasmagoria of Dim. Dream",
	"th04": "Touhou Gensokyo - Lotus Land Story",
	"th05": "Touhou Kaikidan - Mystic Square",
	"th06": "Touhou Koumakyou - The Embodiment of Scarlet Devil",
	"th07": "Touhou Youyoumu - Perfect Cherry Blossom",
	"th08": "Touhou Eiyashou - Imperishable Night",
	"th09": "Touhou Kaeidzuka - Phantasmagoria of Flower View",
	"th095": "Touhou Bunkachou - Shoot the Bullet",
	"th10": "Touhou Fuujinroku - Mountain of Faith",
	"alcostg": "Tasogare Sakaba - Uwabami Breakers",
	"th11": "Touhou Chireiden - Subterranean Animism",
	"th12": "Touhou Seirensen - Undefined Fantastic Object",
	"th125": "Double Spoiler - Touhou Bunkachou",
	"th128": "Yousei Daisensou - Touhou Sangetsusei",
	"th13": "Touhou Shinreibyou - Ten Desires",
	"th14": "Touhou Kishinjou - Double Dealing Character",
	"th143": "Danmaku Amanojaku - Impossible Spell Card",
	"th15": "Touhou Kanjuden - Legacy of Lunatic Kingdom",
	"th16": "Touhou Tenkuushou - Hidden Star in Four Seasons",
	"th165": "Hifuu Nightmare Diary - Violet Detector",
	"th17": "Touhou Kikeijuu - Wily Beast and Weakest Creature",
	"th10 JP": "Touhou Fuujinroku",
	"alcostg JP": "Tasogare Sakaba",
	"th11 JP": "Touhou Chireiden",
	"th12 JP": "Touhou Seirensen",
	"th125 JP": "Double Spoiler",
	"th128 JP": "Yousei Daisensou",
	"th13 JP": "Touhou Shinreibyou",
	"th14 JP": "Touhou Kishinjou",
	"th143 JP": "Danmaku Amanojaku",
	"th15 JP": "Touhou Kanjuden",
	"th16 JP": "Touhou Tenkuushou",
	"th165 JP": "Hifuu Nightmare Diary",
	"th17 JP": "Touhou Kikeijuu",
	"th13 Spell Practice Unknown": " No.%3d  ???????????",
	"th10 Result Unknown Spell": "No. <r$%3d$999>  ????????????????????? <r$%4d/%4d$>",
	"th15 Result Known Spell": "No. <r$%s%s%s$999>  %s <r$%4d/%4d$>",
	"th15 Result Unknown Spell": "No. <r$%s%s%s$999>  ????????????????????? <r$%4d/%4d$>",
	"Music Room Unknown Title": "No. <r$%2d$99>  ???????????",
	"th143 Trophy Unknown": "????????????",
	"th15 Full-width 0": "0",
	"th15 Full-width 1": "1",
	"th15 Full-width 2": "2",
	"th15 Full-width 3": "3",
	"th15 Full-width 4": "4",
	"th15 Full-width 5": "5",
	"th15 Full-width 6": "6",
	"th15 Full-width 7": "7",
	"th15 Full-width 8": "8",
	"th15 Full-width 9": "9"
}
